### ISSUE TITLE
server-side config needs 'allowed_overrides: [workflow]

### ISSUE THREAD

**Issue by romiafrizal** [AlibabaCloudIndonesia/terraform-atlantis-chapter5#7]
Apakah teman-teman ada mengalami ini saat merge request dan selalu outputnya seperti ini:
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

Terraform version: 0.14.x
Atlantis version: v0.17.3

repos.yaml
```
repos:
- id: gitlab.com/xxxx/*
  branch: /.*/
  allowed_overrides: [apply_requirements, workflow]
  allow_custom_workflows: true
  apply_requirements: [approved, mergeable]
```

atlantis.yaml
```
version: 3
projects:
- name: development
  dir: development
  autoplan:
    when_modified: ["*.tf", "./development/**.tf", ]
    enabled: true
  workflow: default

- name: staging
  dir: staging
  autoplan:
    when_modified: ["*.tf", "./staging/**.tf", ]
    enabled: true
  workflow: default

workflows:
  default:
    plan:
      steps:
      - init
      - plan
    apply:
      steps:
      - apply
```
